### ISSUE TITLE
Support feature extraction in XGBoost formats

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/featran#83]
We should add support for feature extraction in `XGBoost` formats: `LabeledPoint`, `DMatrix`, ?

**Comment by richwhitjr** [comment]
LabeledPoint may make sense although I don't think it is serializable so that may be a problem?  We can attempt to solve for it though or just let users deal with it how they want.

DMatrix feels like more of an unknown.  Right now aside from numpy we write one row into one feature type.  Do you think we should save all of the rows into a single DMatrix or store each vector into a single row DMatrix?

**Comment by ravwojdyla** [comment]
@richwhitjr I have not investigated this much, so I have few answers. I believe `LabeledPoint` is [serializable](https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/LabeledPoint.scala) (?)

**Comment by richwhitjr** [comment]
Ah yep, missed that.
